In [8]:
import sys
import numpy as np

In [9]:
sys.path.append('/Users/michael/Documents/GitHub/farkle')

In [10]:
from farkle_sim import analyze_roll, score_roll

In [11]:
import itertools

In [12]:
def parse_hand(hand):
    score = 0
    num_dice = 6
    for i in hand:
        for j in i:
            score += j[1]
            num_dice -= j[2]
            if num_dice == 0:
                num_dice = 6
    return score, num_dice

In [13]:
def get_prob(num_dice):
    comb = itertools.combinations_with_replacement([1,2,3,4,5,6],num_dice)
    comb_list = [np.array(i) for i in comb]
    comb_analyzed = [analyze_roll.get_scorable(i) for i in comb_list]
    comb_scored = [score_roll.count_gathered(i) for i in comb_analyzed]
    parsed = [parse_hand(i) for i in comb_scored]
    
    farkles = []
    for i,j in enumerate(parsed):
        if j[0] == 0:
            farkles.append((comb_list[i],j))
        
    odds = len(farkles)/len(comb_list)
    
    return odds, len(comb_list)

In [40]:
p_comb = itertools.combinations_with_replacement([1,2,3,4,5,6],2)

In [41]:
combs = [np.array(i) for i in p_comb]

In [42]:
combs[0]

array([1, 1])

In [48]:
parse_hand(score_roll.count_gathered(analyze_roll.get_scorable(combs[7])))

(0, 6)

In [47]:
combs

[array([1, 1]),
 array([1, 2]),
 array([1, 3]),
 array([1, 4]),
 array([1, 5]),
 array([1, 6]),
 array([2, 2]),
 array([2, 3]),
 array([2, 4]),
 array([2, 5]),
 array([2, 6]),
 array([3, 3]),
 array([3, 4]),
 array([3, 5]),
 array([3, 6]),
 array([4, 4]),
 array([4, 5]),
 array([4, 6]),
 array([5, 5]),
 array([5, 6]),
 array([6, 6])]

In [7]:
[get_prob(i) for i in range(1,7)]

[(0.6666666666666666, 6),
 (0.47619047619047616, 21),
 (0.2857142857142857, 56),
 (0.15079365079365079, 126),
 (0.06349206349206349, 252),
 (0.012987012987012988, 462)]