In [1]:
import numpy as np

In [2]:
np.random.seed(13)

In [80]:
roll = np.random.randint(1,7,6)

In [81]:
roll

array([3, 1, 5, 4, 1, 5])

In [82]:
np.sum(roll == 6)

0

In [83]:
def count_roll(roll):
    return np.array([np.sum(roll == i) for i in range(1,7)])

In [84]:
counts = count_roll(roll)

In [85]:
counts

array([2, 0, 1, 1, 2, 0])

In [60]:
np.where(counts==3)[0].size

1

In [27]:
vals = [1,2,3,4,5,6]

In [61]:
mix_vals = [2,4,5,3,1,6]

In [63]:
set(vals) == set(mix_vals)

True

In [64]:
vals_arr = np.array([1,2,3,4,5,6])

In [65]:
test_straight = np.array([1,3,4,6,5,2])

In [67]:
np.in1d(test_straight,vals_arr).all()

True

In [97]:
threepair = np.array([1,1,1,1,3,3])

In [100]:
(count_roll(threepair) == 2).sum()

1

In [101]:
(count_roll(threepair) == 4).sum()

1

In [ ]:
rol

In [69]:
np.extract((counts==3),vals_arr)

array([4])

In [128]:
def get_scorable(roll):
    '''
    takes numpy array of counted simulated roll and returns dict
    '''
    counted_roll = count_roll(roll)
    
    scorable = {}
    
    # single dice
    scorable['one'] = counted_roll[0] #count of ones in first (0 index) position
    scorable['five'] = counted_roll[4] #count of fives in fifth (4 index) position
    
    
    # 3 of a kind
    tok_keys = ["three-ones","three-twos","three-threes","three-fours","three-fives","three-sixes"]
    tok_array = counted_roll==3
    for i in range(0,6):
        scorable[tok_keys[i]] = tok_array[i]
        
    
    # combos
    cmb_keys = ["four-of-a-kind","five-of-a-kind","six-of-a-kind","straight","three-pairs","four-and-pair","triplets"]
    straight_array = np.array([1,2,3,4,5,6])
    
    scorable["four-of-a-kind"] = (counted_roll==4).any()
    scorable["five-of-a-kind"] = (counted_roll==5).any()
    scorable["six-of-a-kind"] = (counted_roll==6).any()
    scorable["straight"] = np.isin(straight_array,roll).all()
    scorable["three-pairs"] = ((counted_roll==2).sum()==3)
    scorable["four-and-pair"] = ((counted_roll == 4).any() and (counted_roll == 2).any())
    scorable["triplets"] = ((counted_roll==3).sum()==2)
    
    return scorable
    

In [131]:
get_scorable(np.array([1,2,3,4,5,6]))

{'one': 1,
 'five': 1,
 'three-ones': False,
 'three-twos': False,
 'three-threes': False,
 'three-fours': False,
 'three-fives': False,
 'three-sixes': False,
 'four-of-a-kind': False,
 'five-of-a-kind': False,
 'six-of-a-kind': False,
 'straight': True,
 'three-pairs': False,
 'four-and-pair': False,
 'triplets': False}